defmodule Helpdesk.Repo.Migrations.AddEmbeddedCommentsToTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :comments, {:array, :map}
    end
  end

  def down do
    alter table(:tickets) do
      remove :comments
    end
  end
end
